/// ### English
/// Maps GLFW key codes into W3C `Code` values used by Servo.
/// This is a best-effort mapping for embedder-side key events.
///
/// ### 中文
/// 将 GLFW 键码映射到 Servo 使用的 W3C `Code`。
/// 这是宿主侧键盘事件的尽力映射（best-effort）。
pub(in super::super) fn glfw_key_to_code(glfw_key: u32) -> servo::Code {
    use servo::Code;

    match glfw_key {
        32 => Code::Space,
        39 => Code::Quote,
        44 => Code::Comma,
        45 => Code::Minus,
        46 => Code::Period,
        47 => Code::Slash,
        48 => Code::Digit0,
        49 => Code::Digit1,
        50 => Code::Digit2,
        51 => Code::Digit3,
        52 => Code::Digit4,
        53 => Code::Digit5,
        54 => Code::Digit6,
        55 => Code::Digit7,
        56 => Code::Digit8,
        57 => Code::Digit9,
        59 => Code::Semicolon,
        61 => Code::Equal,
        65 => Code::KeyA,
        66 => Code::KeyB,
        67 => Code::KeyC,
        68 => Code::KeyD,
        69 => Code::KeyE,
        70 => Code::KeyF,
        71 => Code::KeyG,
        72 => Code::KeyH,
        73 => Code::KeyI,
        74 => Code::KeyJ,
        75 => Code::KeyK,
        76 => Code::KeyL,
        77 => Code::KeyM,
        78 => Code::KeyN,
        79 => Code::KeyO,
        80 => Code::KeyP,
        81 => Code::KeyQ,
        82 => Code::KeyR,
        83 => Code::KeyS,
        84 => Code::KeyT,
        85 => Code::KeyU,
        86 => Code::KeyV,
        87 => Code::KeyW,
        88 => Code::KeyX,
        89 => Code::KeyY,
        90 => Code::KeyZ,
        91 => Code::BracketLeft,
        92 => Code::Backslash,
        93 => Code::BracketRight,
        96 => Code::Backquote,

        256 => Code::Escape,
        257 => Code::Enter,
        258 => Code::Tab,
        259 => Code::Backspace,
        260 => Code::Insert,
        261 => Code::Delete,
        262 => Code::ArrowRight,
        263 => Code::ArrowLeft,
        264 => Code::ArrowDown,
        265 => Code::ArrowUp,
        266 => Code::PageUp,
        267 => Code::PageDown,
        268 => Code::Home,
        269 => Code::End,

        280 => Code::CapsLock,
        281 => Code::ScrollLock,
        282 => Code::NumLock,
        283 => Code::PrintScreen,
        284 => Code::Pause,

        290 => Code::F1,
        291 => Code::F2,
        292 => Code::F3,
        293 => Code::F4,
        294 => Code::F5,
        295 => Code::F6,
        296 => Code::F7,
        297 => Code::F8,
        298 => Code::F9,
        299 => Code::F10,
        300 => Code::F11,
        301 => Code::F12,

        320 => Code::Numpad0,
        321 => Code::Numpad1,
        322 => Code::Numpad2,
        323 => Code::Numpad3,
        324 => Code::Numpad4,
        325 => Code::Numpad5,
        326 => Code::Numpad6,
        327 => Code::Numpad7,
        328 => Code::Numpad8,
        329 => Code::Numpad9,
        330 => Code::NumpadDecimal,
        331 => Code::NumpadDivide,
        332 => Code::NumpadMultiply,
        333 => Code::NumpadSubtract,
        334 => Code::NumpadAdd,
        335 => Code::NumpadEnter,
        336 => Code::NumpadEqual,

        340 => Code::ShiftLeft,
        341 => Code::ControlLeft,
        342 => Code::AltLeft,
        343 => Code::MetaLeft,
        344 => Code::ShiftRight,
        345 => Code::ControlRight,
        346 => Code::AltRight,
        347 => Code::MetaRight,
        348 => Code::ContextMenu,

        _ => Code::Unidentified,
    }
}
