name: Check

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    name: Check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      actions: write
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: "true"
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends libfontconfig1-dev pkg-config lld

      - name: Cargo Check
        run: |
          cargo check --locked
